/** Provisioning-helper actions for Site tools (no customer-facing phase labels). */

export const SITE_TOOLS_READ = [
  "dmarc-get",
  "deliverability-dashboard",
  "mailbox-autoreply-list",
  "mail-bounces-list",
  "bounce-suppress-list",
  "newsletter-stats-get",
  "newsletter-gdpr-export",
  "newsletter-templates-list",
  "newsletter-segments-list",
  "analytics-summary",
  "analytics-history",
  "git-deploy-get",
  "git-deploy-log",
  "wp-toolkit-status",
  "wp-toolkit-security",
  "woocommerce-status",
  "maintenance-get",
  "contact-form-get",
  "contact-form-embed",
  "staging-get",
  "bandwidth-usage",
  "bandwidth-traffic",
  "redis-get",
  "memcached-get",
  "ssh-keys-list",
  "awstats-config",
  "awstats-run",
  "seo-404-scan",
  "ci-pipeline-get",
  "tickets-list",
  "billing-invoices-list",
  "carddav-status",
  "carddav-export-vcf",
] as const;

export const SITE_TOOLS_WRITE = [
  "dmarc-set",
  "mailbox-autoreply-set",
  "mailbox-autoreply-apply",
  "bounce-suppress-add",
  "newsletter-template-save",
  "newsletter-segment-save",
  "git-deploy-set",
  "git-deploy-run",
  "git-deploy-rollback",
  "wp-toolkit-update",
  "wp-toolkit-plugins",
  "wp-toolkit-backup",
  "maintenance-set",
  "maintenance-nginx",
  "contact-form-set",
  "staging-sync",
  "staging-promote",
  "staging-vhost",
  "redis-set",
  "memcached-set",
  "mongo-create",
  "ssh-keys-add",
  "ssh-keys-delete",
  "subdomain-add",
  "ci-pipeline-set",
  "ci-pipeline-run",
  "tickets-create",
  "tickets-reply",
  "ticket-notify",
  "billing-invoice-create",
  "invoice-mark-sent",
  "carddav-contact-upsert",
] as const;
