#!/usr/bin/env bash
# Nginx vhost: panel.<domain> → Qadbak Next.js (:3000) and terminal WS (:3001).
# Usage: sudo bash scripts/apply-client-panel-vhost.sh example.com
#        sudo bash scripts/apply-client-panel-vhost.sh __probe__
#
# Notes on the listen lines (see docs/HOSTING-NGINX.md, "Client panel access"):
#   - server_name is ALWAYS just panel.<domain>. We never claim `_` or
#     `default_server` here — those slots belong to the main panel vhost
#     (deploy/nginx-qadbak.conf) and the default-deny vhost
#     (scripts/apply-nginx-default-deny.sh). Claiming them a second time
#     produces `[warn] conflicting server name "_"` and crashes nginx
#     with `[emerg] a duplicate default server`.
#   - The HTTPS listener is `listen 443 ssl;` WITHOUT `http2`. The main
#     panel vhost already declares `http2` on the same listener pair;
#     http2 is a per-listener protocol option and repeating it produces
#     `[warn] protocol options redefined for 0.0.0.0:443`. nginx still
#     speaks HTTP/2 here because the listener-wide option from the main
#     vhost wins.
#   - We render the full HTTP + HTTPS vhost ourselves and obtain the
#     cert with `certbot certonly --nginx` so certbot's installer never
#     rewrites this file (which is what historically introduced the
#     `http2 on;` / duplicate-listen warnings).
set -euo pipefail

ROOT="${QADBAK_DIR:-/opt/qadbak}"
DOMAIN="${1:-}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi

if [[ "$DOMAIN" == "__probe__" ]]; then
  echo "OK"
  exit 0
fi

if [[ -z "$DOMAIN" ]] || [[ "$DOMAIN" == *"/"* ]] || [[ "$DOMAIN" == *" "* ]]; then
  echo "Usage: sudo bash scripts/apply-client-panel-vhost.sh <domain>" >&2
  exit 1
fi

DOMAIN="$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]')"
PANEL_HOST="panel.${DOMAIN}"
SAFE="${DOMAIN//./-}"
OUT="/etc/nginx/sites-available/qadbak-panel-${SAFE}.conf"
ENABLED="/etc/nginx/sites-enabled/qadbak-panel-${SAFE}.conf"

LE_EMAIL=""
if [[ -f "$ROOT/.env.local" ]]; then
  LE_EMAIL="$(grep -E '^QADBAK_LE_EMAIL=' "$ROOT/.env.local" | cut -d= -f2- | tr -d '"' || true)"
  [[ -z "$LE_EMAIL" ]] && LE_EMAIL="$(grep -E '^LE_EMAIL=' "$ROOT/.env.local" | cut -d= -f2- | tr -d '"' || true)"
fi
if [[ -z "$LE_EMAIL" ]]; then
  LE_EMAIL="admin@${DOMAIN}"
fi

SERVER_IP="$(curl -4 -fsS --max-time 3 ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
SERVER_IP="${SERVER_IP:-<server-ip>}"

echo "==> DNS A record for ${PANEL_HOST}"
echo "    If this is the first panel vhost for ${DOMAIN}, also add an external"
echo "    DNS A-record so the customer can reach the panel:"
echo "      ${PANEL_HOST}.  A  ${SERVER_IP}"
bash "$ROOT/scripts/ensure-panel-dns-a.sh" "$DOMAIN" || true

write_proxy_locations() {
  cat <<'NGX'
    location /ws/domain-terminal {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
NGX
}

write_vhost() {
  local has_cert="$1"
  echo "# Qadbak client panel — ${PANEL_HOST}"
  echo "# Generated by scripts/apply-client-panel-vhost.sh — do not edit by hand."
  echo "# server_name is intentionally NOT '_' / default_server; see script header."
  if [[ "$has_cert" == "1" ]]; then
    echo "server {"
    echo "    listen 80;"
    echo "    listen [::]:80;"
    echo "    server_name ${PANEL_HOST};"
    echo ""
    echo "    location ^~ /.well-known/acme-challenge/ {"
    echo "        root /var/www/html;"
    echo "        try_files \$uri =404;"
    echo "    }"
    echo "    # Proxy on :80 (required for Cloudflare Flexible — do not force HTTPS redirect)"
    write_proxy_locations
    echo "}"
    echo ""
    echo "server {"
    # listen 443 ssl (no http2 — the main panel vhost already set it on
    # this listener pair; repeating it triggers "protocol options redefined").
    echo "    listen 443 ssl;"
    echo "    listen [::]:443 ssl;"
    echo "    server_name ${PANEL_HOST};"
    echo ""
    echo "    ssl_certificate     /etc/letsencrypt/live/${PANEL_HOST}/fullchain.pem;"
    echo "    ssl_certificate_key /etc/letsencrypt/live/${PANEL_HOST}/privkey.pem;"
    echo ""
    echo "    client_max_body_size 0;"
    echo ""
    write_proxy_locations
    echo "}"
  else
    echo "server {"
    echo "    listen 80;"
    echo "    listen [::]:80;"
    echo "    server_name ${PANEL_HOST};"
    echo ""
    echo "    client_max_body_size 0;"
    echo ""
    write_proxy_locations
    echo "}"
  fi
}

# First pass: HTTP-only vhost so certbot --nginx can solve HTTP-01.
write_vhost 0 >"$OUT"
ln -sf "$OUT" "$ENABLED"
nginx -t
systemctl reload nginx

HAS_CERT=0
if [[ -f "/etc/letsencrypt/live/${PANEL_HOST}/fullchain.pem" ]]; then
  HAS_CERT=1
elif [[ -n "$LE_EMAIL" ]] && command -v certbot &>/dev/null; then
  PANEL_PUBLIC_IP=""
  if command -v dig &>/dev/null; then
    PANEL_PUBLIC_IP="$(dig +short A "$PANEL_HOST" @8.8.8.8 2>/dev/null | grep -E '^[0-9.]+$' | head -1 || true)"
  fi
  if [[ -z "$PANEL_PUBLIC_IP" ]]; then
    echo "    SKIP TLS — no public DNS A record for ${PANEL_HOST} yet (add at registrar: A → ${SERVER_IP})" >&2
    echo "          Panel works on http://${PANEL_HOST}/ until DNS + certbot succeed." >&2
  else
    echo "==> TLS for ${PANEL_HOST} (Let's Encrypt, ${LE_EMAIL}) — DNS → ${PANEL_PUBLIC_IP}"
    if certbot certonly --nginx -d "$PANEL_HOST" \
         --non-interactive --agree-tos -m "$LE_EMAIL" --keep-until-expiring; then
      HAS_CERT=1
      echo "    OK — Let's Encrypt cert issued for ${PANEL_HOST}"
    else
      echo "    WARN: certbot failed — use http://${PANEL_HOST}/ until DNS propagates, then re-run this script" >&2
      echo "          Most common cause: A-record for ${PANEL_HOST} not yet pointing at ${SERVER_IP}" >&2
    fi
  fi
fi

# Second pass: now that the cert state is known, write the final vhost.
write_vhost "$HAS_CERT" >"$OUT"
ln -sf "$OUT" "$ENABLED"
nginx -t
systemctl reload nginx

if [[ -f "$ROOT/scripts/lib/sanitize-nginx-panel-vhosts.sh" ]]; then
  bash "$ROOT/scripts/lib/sanitize-nginx-panel-vhosts.sh" 2>/dev/null || true
fi

if [[ "$HAS_CERT" == "1" ]]; then
  echo "OK — https://${PANEL_HOST}/login"
else
  echo "OK — http://${PANEL_HOST}/login (HTTPS pending — fix DNS then re-run this script)"
fi
