#!/usr/bin/env bash
# Install sudoers rule for Qadbak native file manager (existing servers).
set -euo pipefail

QADBAK_DIR="${QADBAK_DIR:-/opt/qadbak}"
QADBAK_USER="${QADBAK_USER:-qadbak}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash scripts/configure-domain-fs-sudo.sh" >&2
  exit 1
fi

HELPER="$(readlink -f "$QADBAK_DIR/scripts/domain-fs-helper.mjs")"
WRAPPER="$(readlink -f "$QADBAK_DIR/scripts/run-domain-fs-helper.sh")"
if [[ ! -f "$HELPER" ]]; then
  echo "Missing $HELPER — git pull in $QADBAK_DIR first." >&2
  exit 1
fi

# Node path must match what the qadbak/pm2 process uses (not necessarily root's PATH).
NODE_BIN="$(sudo -u "$QADBAK_USER" -H bash -lc 'command -v node' 2>/dev/null | head -1)"
if [[ -z "$NODE_BIN" || ! -x "$NODE_BIN" ]]; then
  NODE_BIN="$(command -v node)"
fi
if [[ -z "$NODE_BIN" ]]; then
  echo "node not found for user $QADBAK_USER" >&2
  exit 1
fi
NODE_BIN="$(readlink -f "$NODE_BIN")"

chmod 755 "$HELPER"
cat >"$WRAPPER" <<EOF
#!/bin/bash
# Generated by configure-domain-fs-sudo.sh — do not edit by hand.
set -euo pipefail
exec '$NODE_BIN' '$HELPER' "\$@"
EOF
chmod 755 "$WRAPPER"

SUDOERS="/etc/sudoers.d/qadbak-domain-fs"
cat >"$SUDOERS" <<EOF
# Qadbak native file browser — list/read/write under /home/
$QADBAK_USER ALL=(root) NOPASSWD: $WRAPPER *
EOF
chmod 440 "$SUDOERS"
visudo -cf "$SUDOERS"

echo "==> Verify file helper sudo (must return ok JSON)"
TEST_HOME="$(getent passwd | awk -F: '$6 ~ /^\/home\/[^/]+$/ {print $6; exit}')"
TEST_HOME="${TEST_HOME:-/home}"
if ! sudo -u "$QADBAK_USER" sudo -n "$WRAPPER" list "$TEST_HOME" 2>/dev/null | grep -q '"ok"'; then
  echo "FAILED: sudo rule not active. Check:" >&2
  echo "  cat $SUDOERS" >&2
  echo "  sudo -u $QADBAK_USER sudo -l" >&2
  exit 1
fi

echo "OK — wrapper: $WRAPPER"
echo "     node:    $NODE_BIN"
