#!/usr/bin/env bash
# Minimal nginx reverse proxy for panel-only installs (no Apache/customer vhosts).
set -euo pipefail

QADBAK_DIR="${QADBAK_DIR:-/opt/qadbak}"
PORT="${PORT:-3000}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash scripts/install-panel-nginx.sh" >&2
  exit 1
fi

# shellcheck source=lib/linux-distro.sh
source "$(dirname "$0")/lib/linux-distro.sh"
# shellcheck source=lib/nginx-listen.sh
source "$(dirname "$0")/lib/nginx-listen.sh"

PANEL_HOST=""
if [[ -f "$QADBAK_DIR/.env.local" ]]; then
  PANEL_HOST="$(grep '^QADBAK_PUBLIC_HOST=' "$QADBAK_DIR/.env.local" | cut -d= -f2- | tr -d '"' || true)"
fi
PANEL_HOST="${PANEL_HOST:-${1:-$(hostname -f 2>/dev/null || hostname)}}"

if ! qadbak_has_apt; then
  echo "Panel nginx helper requires apt (Debian/Ubuntu). Proxy port $PORT manually." >&2
  exit 1
fi

qadbak_pkg_install nginx
DEFAULT_SERVER_KW="$(panel_default_server_keyword)"
CONF="/etc/nginx/sites-available/qadbak-panel-only"
ENABLED="/etc/nginx/sites-enabled/qadbak-panel-only"

cat >"$CONF" <<EOF
# Qadbak panel-only reverse proxy — generated by install-panel-nginx.sh
server {
    listen 80${DEFAULT_SERVER_KW};
    listen [::]:80${DEFAULT_SERVER_KW};
    server_name ${PANEL_HOST};

    client_max_body_size 100m;

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

ln -sf "$CONF" "$ENABLED"
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
nginx -t
systemctl enable nginx
systemctl reload nginx

LE_EMAIL=""
if [[ -f "$QADBAK_DIR/.env.local" ]]; then
  LE_EMAIL="$(grep '^QADBAK_LE_EMAIL=' "$QADBAK_DIR/.env.local" | cut -d= -f2- || true)"
fi
if [[ -n "${LE_EMAIL// }" ]] && command -v certbot &>/dev/null; then
  qadbak_pkg_install certbot python3-certbot-nginx 2>/dev/null || true
  if certbot --nginx -d "$PANEL_HOST" --non-interactive --agree-tos -m "$LE_EMAIL" --redirect; then
    if grep -q '^QADBAK_COOKIE_SECURE=' "$QADBAK_DIR/.env.local" 2>/dev/null; then
      sed -i 's/^QADBAK_COOKIE_SECURE=.*/QADBAK_COOKIE_SECURE=true/' "$QADBAK_DIR/.env.local"
    else
      echo "QADBAK_COOKIE_SECURE=true" >>"$QADBAK_DIR/.env.local"
    fi
    echo "OK — HTTPS enabled for $PANEL_HOST"
  fi
fi

echo "OK — panel nginx proxy: http://${PANEL_HOST}/ → 127.0.0.1:${PORT}"
